In [8]:
import pandas as pd
import numpy as np

In [9]:
korean_f0 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f0.csv")
korean_f10 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f10.csv")
korean_f20 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f20.csv")
korean_f30 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f30.csv")
korean_f40 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f40.csv")
korean_f50 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f50.csv")
korean_f60 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f60.csv")
korean_f70 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f70.csv")
korean_f80 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f80.csv")

korean_m0 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m0.csv")
korean_m10 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m10.csv")
korean_m20 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m20.csv")
korean_m30 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m30.csv")
korean_m40 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m40.csv")
korean_m50 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m50.csv")
korean_m60 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m60.csv")
korean_m70 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m70.csv")
korean_m80 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m80.csv")

waste = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\1_food_waste_preprocessing.csv")

In [12]:
data_merge = pd.merge(korean_f0, korean_f10, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f20, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f30, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f40, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f50, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f60, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f70, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f80, on=['base_date', 'emd_cd'])

data_merge = pd.merge(data_merge, korean_m0, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m10, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m20, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m30, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m40, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m50, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m60, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m70, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m80, on=['base_date', 'emd_cd'])

data_merge = pd.merge(data_merge, waste, on=['base_date', 'emd_cd'])
data_merge = data_merge.drop(['em_cnt'], 1)
data_merge

,base_date,emd_cd,f0_resd_pop,f0_work_pop,f0_visit_pop,f10_resd_pop,f10_work_pop,f10_visit_pop,f20_resd_pop,f20_work_pop,...,m60_resd_pop,m60_work_pop,m60_visit_pop,m70_resd_pop,m70_work_pop,m70_visit_pop,m80_resd_pop,m80_work_pop,m80_visit_pop,em_g
0,2019-11-30,50110250,595656.6904,75850.2547,244450.7884,470973.4183,58210.9861,190021.1853,320859.0111,35541.8894,...,9.803283e+05,64510.8733,412777.5716,462903.2294,14949.1031,130905.9135,316369.2533,8414.2938,71774.4096,2279550
1,2019-12-31,50110250,652151.7585,61500.4928,226945.5000,515642.8981,47098.8555,176849.9974,332910.6583,31108.4411,...,1.042920e+06,54769.1474,356647.7173,475781.6367,14572.9457,133060.6767,325170.9463,8482.1220,73314.9065,31493650
2,2020-01-31,50110250,636463.4354,27210.6699,399362.9784,503238.4661,21032.9124,311991.9034,331482.3683,38458.0489,...,1.039688e+06,63895.7106,345317.5147,498917.8941,9754.4773,97718.5716,340983.3250,5471.7085,54101.8748,49632850
3,2020-02-29,50110250,602907.6061,10699.8444,188481.2982,476706.5663,8391.0285,146962.6067,327308.5271,27226.7952,...,9.829013e+05,68664.7858,329660.2978,470861.8783,10751.8373,102608.8361,321808.5589,6080.5963,56601.9260,46197050
4,2020-03-31,50110250,642258.4013,11387.4048,183057.2598,507820.4275,8839.0273,142351.2402,349132.2653,24328.9595,...,1.081765e+06,66324.8183,374835.4358,525689.0973,24380.3455,110250.7900,359279.9913,13307.4003,61633.6654,52561750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,2021-02-28,50130620,106554.7117,515.3878,188420.8433,69829.5432,393.8831,147680.5081,124420.8042,69683.5399,...,1.615357e+05,33944.3906,185865.3256,96869.1285,3392.4050,60849.0952,72584.3886,1813.6854,33586.5245,15566250
1630,2021-03-31,50130620,100670.5675,1651.9066,70897.6992,65973.4305,1264.1962,55205.7049,137125.1918,79959.4419,...,1.752911e+05,38533.5056,245080.5467,109278.5526,5560.0581,72014.7975,81882.8147,2958.7652,39916.2166,17300600
1631,2021-04-30,50130620,94585.3320,1265.9660,79003.5640,61985.5337,967.5094,61643.0341,145934.6720,82938.6389,...,1.653582e+05,39654.5395,276591.1410,107051.8896,2540.5234,81552.0756,80214.3661,1376.1945,44899.0090,17646850
1632,2021-05-31,50130620,102822.4935,2202.7842,141224.2364,67383.6726,1688.2686,110464.9987,158768.6248,89178.4000,...,1.760794e+05,38623.3075,265545.3991,103384.6804,4546.0320,81058.3047,77466.5160,2647.8493,44401.0198,19494750
1633,2021-06-30,50130620,98120.6208,1145.2322,134030.4870,64302.3493,884.2088,104929.5216,148594.3741,78142.3558,...,1.588043e+05,42713.8115,253191.3618,95661.6527,3448.9277,70244.7161,71679.6237,1985.0294,38584.3209,18753350

In [13]:
data_merge.columns = ['base_date', 'emd_cd', 
                      'korean_resd_f0', 'korean_work_f0', 'korean_visit_f0', 
                      'korean_resd_f10', 'korean_work_f10', 'korean_visit_f10', 
                      'korean_resd_f20', 'korean_work_f20', 'korean_visit_f20', 
                      'korean_resd_f30', 'korean_work_f30', 'korean_visit_f30', 
                      'korean_resd_f40', 'korean_work_f40', 'korean_visit_f40', 
                      'korean_resd_f50', 'korean_work_f50', 'korean_visit_f50', 
                      'korean_resd_f60', 'korean_work_f60', 'korean_visit_f60', 
                      'korean_resd_f70', 'korean_work_f70', 'korean_visit_f70', 
                      'korean_resd_f80', 'korean_work_f80', 'korean_visit_f80', 
                      'korean_resd_m0', 'korean_work_m0', 'korean_visit_m0', 
                      'korean_resd_m10', 'korean_work_m10', 'korean_visit_m10', 
                      'korean_resd_m20', 'korean_work_m20', 'korean_visit_m20', 
                      'korean_resd_m30', 'korean_work_m30', 'korean_visit_m30', 
                      'korean_resd_m40', 'korean_work_m40', 'korean_visit_m40', 
                      'korean_resd_m50', 'korean_work_m50', 'korean_visit_m50', 
                      'korean_resd_m60', 'korean_work_m60', 'korean_visit_m60', 
                      'korean_resd_m70', 'korean_work_m70', 'korean_visit_m70', 
                      'korean_resd_m80', 'korean_work_m80', 'korean_visit_m80',
                     'waste_amt']
data_merge

,base_date,emd_cd,korean_resd_f0,korean_work_f0,korean_visit_f0,korean_resd_f10,korean_work_f10,korean_visit_f10,korean_resd_f20,korean_work_f20,...,korean_resd_m60,korean_work_m60,korean_visit_m60,korean_resd_m70,korean_work_m70,korean_visit_m70,korean_resd_m80,korean_work_m80,korean_visit_m80,waste_amt
0,2019-11-30,50110250,595656.6904,75850.2547,244450.7884,470973.4183,58210.9861,190021.1853,320859.0111,35541.8894,...,9.803283e+05,64510.8733,412777.5716,462903.2294,14949.1031,130905.9135,316369.2533,8414.2938,71774.4096,2279550
1,2019-12-31,50110250,652151.7585,61500.4928,226945.5000,515642.8981,47098.8555,176849.9974,332910.6583,31108.4411,...,1.042920e+06,54769.1474,356647.7173,475781.6367,14572.9457,133060.6767,325170.9463,8482.1220,73314.9065,31493650
2,2020-01-31,50110250,636463.4354,27210.6699,399362.9784,503238.4661,21032.9124,311991.9034,331482.3683,38458.0489,...,1.039688e+06,63895.7106,345317.5147,498917.8941,9754.4773,97718.5716,340983.3250,5471.7085,54101.8748,49632850
3,2020-02-29,50110250,602907.6061,10699.8444,188481.2982,476706.5663,8391.0285,146962.6067,327308.5271,27226.7952,...,9.829013e+05,68664.7858,329660.2978,470861.8783,10751.8373,102608.8361,321808.5589,6080.5963,56601.9260,46197050
4,2020-03-31,50110250,642258.4013,11387.4048,183057.2598,507820.4275,8839.0273,142351.2402,349132.2653,24328.9595,...,1.081765e+06,66324.8183,374835.4358,525689.0973,24380.3455,110250.7900,359279.9913,13307.4003,61633.6654,52561750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,2021-02-28,50130620,106554.7117,515.3878,188420.8433,69829.5432,393.8831,147680.5081,124420.8042,69683.5399,...,1.615357e+05,33944.3906,185865.3256,96869.1285,3392.4050,60849.0952,72584.3886,1813.6854,33586.5245,15566250
1630,2021-03-31,50130620,100670.5675,1651.9066,70897.6992,65973.4305,1264.1962,55205.7049,137125.1918,79959.4419,...,1.752911e+05,38533.5056,245080.5467,109278.5526,5560.0581,72014.7975,81882.8147,2958.7652,39916.2166,17300600
1631,2021-04-30,50130620,94585.3320,1265.9660,79003.5640,61985.5337,967.5094,61643.0341,145934.6720,82938.6389,...,1.653582e+05,39654.5395,276591.1410,107051.8896,2540.5234,81552.0756,80214.3661,1376.1945,44899.0090,17646850
1632,2021-05-31,50130620,102822.4935,2202.7842,141224.2364,67383.6726,1688.2686,110464.9987,158768.6248,89178.4000,...,1.760794e+05,38623.3075,265545.3991,103384.6804,4546.0320,81058.3047,77466.5160,2647.8493,44401.0198,19494750
1633,2021-06-30,50130620,98120.6208,1145.2322,134030.4870,64302.3493,884.2088,104929.5216,148594.3741,78142.3558,...,1.588043e+05,42713.8115,253191.3618,95661.6527,3448.9277,70244.7161,71679.6237,1985.0294,38584.3209,18753350

In [5]:
data_merge.to_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\ver_2_3_merge_data.csv", index_label=False)

In [6]:
pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\ver_2_3_merge_data.csv")

,base_date,emd_cd,korean_resd_f0,korean_work_f0,korean_visit_f0,korean_resd_f10,korean_work_f10,korean_visit_f10,korean_resd_f20,korean_work_f20,...,korean_visit_m50,korean_resd_m60,korean_work_m60,korean_visit_m60,korean_resd_m70,korean_work_m70,korean_visit_m70,korean_resd_m80,korean_work_m80,korean_visit_m80
0,2018-01-31,50110250,493824.8478,15342.1164,267484.3647,516953.3539,16923.4298,302208.5804,426198.2518,35429.8296,...,654687.1978,868909.8474,51784.6323,336561.2347,445276.0512,14894.2902,90850.8253,189754.4428,5660.5076,34563.4792
1,2018-02-28,50110250,455766.1908,6749.6599,202078.4104,477112.2025,7632.0225,227138.8817,409598.9308,27199.3733,...,502917.7361,773362.0961,45374.7220,266525.7824,384319.5954,15145.2300,83372.3360,163777.8415,5781.2809,31723.3825
2,2018-03-31,50110250,451979.0261,5004.5366,265750.5454,473147.6635,5484.6297,296872.8841,404489.8631,36826.1924,...,738092.7513,852268.0145,48442.6676,400619.5217,419091.0768,15149.3916,136002.4079,178595.7130,5758.1662,51710.3993
3,2018-04-30,50110250,435161.3297,41333.6153,344291.0665,455542.3014,45298.8160,388697.6827,371071.7989,40108.0464,...,732090.4992,812183.3201,64236.6519,429508.9723,407912.2065,16139.0462,186627.5511,173831.8362,6158.6789,70903.7915
4,2018-05-31,50110250,451480.1993,54618.4275,449567.2292,472625.4742,59982.6884,509419.1760,364683.6111,42162.0875,...,688887.9738,857207.4420,49834.1344,396755.5776,437688.9283,23214.0081,155017.8687,186521.1899,8836.0668,58929.3862
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801,2021-02-28,50130620,106554.7117,515.3878,188420.8433,69829.5432,393.8831,147680.5081,124420.8042,69683.5399,...,322127.3700,161535.6882,33944.3906,185865.3256,96869.1285,3392.4050,60849.0952,72584.3886,1813.6854,33586.5245
1802,2021-03-31,50130620,100670.5675,1651.9066,70897.6992,65973.4305,1264.1962,55205.7049,137125.1918,79959.4419,...,368623.6627,175291.0543,38533.5056,245080.5467,109278.5526,5560.0581,72014.7975,81882.8147,2958.7652,39916.2166
1803,2021-04-30,50130620,94585.3320,1265.9660,79003.5640,61985.5337,967.5094,61643.0341,145934.6720,82938.6389,...,390978.7526,165358.2431,39654.5395,276591.1410,107051.8896,2540.5234,81552.0756,80214.3661,1376.1945,44899.0090
1804,2021-05-31,50130620,102822.4935,2202.7842,141224.2364,67383.6726,1688.2686,110464.9987,158768.6248,89178.4000,...,414994.8739,176079.4480,38623.3075,265545.3991,103384.6804,4546.0320,81058.3047,77466.5160,2647.8493,44401.0198
1805,2021-06-30,50130620,98120.6208,1145.2322,134030.4870,64302.3493,884.2088,104929.5216,148594.3741,78142.3558,...,392073.5437,158804.3471,42713.8115,253191.3618,95661.6527,3448.9277,70244.7161,71679.6237,1985.0294,38584.3209