In [1]:
import pandas as pd
import numpy as np

In [4]:
data1 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\1_food_waste_preprocessing.csv")
data2_1 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\2_1_korean_preprocessing_v2.csv")
data2_2 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\2_2_long_term_frgn_preprocessing_v2.csv")
data2_3 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\2_3_short_term_frgn_3_resident_pop_preprocessing.csv")
data3 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\resident_pop_processing2(sex).csv")
data4 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\4_card_spending_ver2.csv")

In [6]:
data_merge = pd.merge(data2_1, data2_2, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data2_3, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data3, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data4, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data1, on=['base_date', 'emd_cd'])
data_merge = data_merge.drop(['total_pop'], 1)
data_merge

,base_date,emd_cd,resd_pop_cnt_x,work_pop_cnt_x,visit_pop_cnt_x,resd_pop_cnt_y,work_pop_cnt_y,visit_pop_cnt_y,visit_pop_cnt,fe_resid_reg_pop,fe_foreign_pop,m_resid_reg_pop,m_foreign_pop,use_cnt_home,use_amt_home,use_cnt_out,use_amt_out,em_cnt,em_g
0,2019-11-30,50110250,1.271267e+07,1.446387e+06,5.875401e+06,811872.3300,95124.9987,374564.3540,129161.4006,10377,1353,11023,2396,301.620000,1.176953e+07,235.281250,7.540087e+06,620,2279550
1,2019-12-31,50110250,1.328514e+07,1.231725e+06,5.683448e+06,786204.8681,76167.6125,406752.6260,122124.6609,10354,1332,11011,2383,295.567742,1.175619e+07,239.472393,7.592077e+06,8178,31493650
2,2020-01-31,50110250,1.322148e+07,1.009434e+06,6.466703e+06,820791.3342,105162.4135,482137.5505,112758.3034,10369,1328,11004,2375,290.387097,1.201056e+07,226.043478,7.374075e+06,13042,49632850
3,2020-02-29,50110250,1.269528e+07,9.268498e+05,4.635128e+06,778132.5491,90134.7711,469304.6248,60252.7989,10341,1328,10985,2367,275.468966,1.023490e+07,224.297297,7.316381e+06,12264,46197050
4,2020-03-31,50110250,1.389778e+07,9.606578e+05,5.133711e+06,841049.3554,103988.5098,610456.5714,29661.4429,10310,1322,10970,2340,290.870968,1.066116e+07,232.694805,7.287016e+06,14316,52561750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,2021-02-28,50130620,2.215681e+06,4.711373e+05,3.850127e+06,131090.2409,21260.3645,88065.1221,280.6159,1904,137,2013,119,74.918519,3.094460e+06,53.826087,1.723436e+06,4563,15566250
1630,2021-03-31,50130620,2.345047e+06,5.526314e+05,4.191678e+06,135195.9186,24214.5837,94044.3054,1475.8404,1918,137,2007,116,73.897959,3.175512e+06,60.849624,1.906193e+06,4920,17300600
1631,2021-04-30,50130620,2.282004e+06,5.918539e+05,4.644853e+06,137049.8002,24437.3744,104790.3736,1283.0997,1904,135,2004,118,74.993151,2.940971e+06,61.398438,1.939595e+06,5256,17646850
1632,2021-05-31,50130620,2.387585e+06,6.403488e+05,5.165064e+06,148574.6128,30121.6614,114091.6036,1212.2652,1910,135,2021,112,80.437908,3.820713e+06,57.283688,1.826895e+06,6346,19494750
1633,2021-06-30,50130620,2.277156e+06,6.271895e+05,5.078006e+06,135610.7887,26114.9422,120841.7426,1194.0627,1902,128,2013,109,79.462585,3.001846e+06,58.548387,1.696647e+06,6328,18753350

In [7]:
data_merge.columns = ['base_date', 'emd_cd', 'korean_resd', 'korean_work', 'korean_visit', 'long_term_frgn_resd', 'long_term_frgn_work', 'long_term_frgn_visit', 'short_term_frgn_visit', 'resident_fe_korean', 'resident_fe_frgn', 'resident_m_korean', 'resident_m_frgn', 'card_cnt_home', 'card_amt_home', 'card_cnt_out', 'card_amt_out', 'waste_cnt', 'waste_amt']
data_merge

,base_date,emd_cd,korean_resd,korean_work,korean_visit,long_term_frgn_resd,long_term_frgn_work,long_term_frgn_visit,short_term_frgn_visit,resident_fe_korean,resident_fe_frgn,resident_m_korean,resident_m_frgn,card_cnt_home,card_amt_home,card_cnt_out,card_amt_out,waste_cnt,waste_amt
0,2019-11-30,50110250,1.271267e+07,1.446387e+06,5.875401e+06,811872.3300,95124.9987,374564.3540,129161.4006,10377,1353,11023,2396,301.620000,1.176953e+07,235.281250,7.540087e+06,620,2279550
1,2019-12-31,50110250,1.328514e+07,1.231725e+06,5.683448e+06,786204.8681,76167.6125,406752.6260,122124.6609,10354,1332,11011,2383,295.567742,1.175619e+07,239.472393,7.592077e+06,8178,31493650
2,2020-01-31,50110250,1.322148e+07,1.009434e+06,6.466703e+06,820791.3342,105162.4135,482137.5505,112758.3034,10369,1328,11004,2375,290.387097,1.201056e+07,226.043478,7.374075e+06,13042,49632850
3,2020-02-29,50110250,1.269528e+07,9.268498e+05,4.635128e+06,778132.5491,90134.7711,469304.6248,60252.7989,10341,1328,10985,2367,275.468966,1.023490e+07,224.297297,7.316381e+06,12264,46197050
4,2020-03-31,50110250,1.389778e+07,9.606578e+05,5.133711e+06,841049.3554,103988.5098,610456.5714,29661.4429,10310,1322,10970,2340,290.870968,1.066116e+07,232.694805,7.287016e+06,14316,52561750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,2021-02-28,50130620,2.215681e+06,4.711373e+05,3.850127e+06,131090.2409,21260.3645,88065.1221,280.6159,1904,137,2013,119,74.918519,3.094460e+06,53.826087,1.723436e+06,4563,15566250
1630,2021-03-31,50130620,2.345047e+06,5.526314e+05,4.191678e+06,135195.9186,24214.5837,94044.3054,1475.8404,1918,137,2007,116,73.897959,3.175512e+06,60.849624,1.906193e+06,4920,17300600
1631,2021-04-30,50130620,2.282004e+06,5.918539e+05,4.644853e+06,137049.8002,24437.3744,104790.3736,1283.0997,1904,135,2004,118,74.993151,2.940971e+06,61.398438,1.939595e+06,5256,17646850
1632,2021-05-31,50130620,2.387585e+06,6.403488e+05,5.165064e+06,148574.6128,30121.6614,114091.6036,1212.2652,1910,135,2021,112,80.437908,3.820713e+06,57.283688,1.826895e+06,6346,19494750
1633,2021-06-30,50130620,2.277156e+06,6.271895e+05,5.078006e+06,135610.7887,26114.9422,120841.7426,1194.0627,1902,128,2013,109,79.462585,3.001846e+06,58.548387,1.696647e+06,6328,18753350

In [8]:
data_merge.to_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\ver_2_merge_data.csv", index_label=False)