In [8]:
import pandas as pd
import numpy as np

In [9]:
data1 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\1_food_waste_preprocessing.csv")
data2_2 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\2_2_long_term_frgn_preprocessing_v2.csv")
data2_3 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\2_3_short_term_frgn_3_resident_pop_preprocessing.csv")
data3 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\resident_pop_processing2(sex).csv")
data4 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\4_card_spending_ver2.csv")

korean_f0 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f0.csv")
korean_f10 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f10.csv")
korean_f20 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f20.csv")
korean_f30 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f30.csv")
korean_f40 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f40.csv")
korean_f50 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f50.csv")
korean_f60 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f60.csv")
korean_f70 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f70.csv")
korean_f80 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_f80.csv")

korean_m0 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m0.csv")
korean_m10 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m10.csv")
korean_m20 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m20.csv")
korean_m30 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m30.csv")
korean_m40 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m40.csv")
korean_m50 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m50.csv")
korean_m60 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m60.csv")
korean_m70 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m70.csv")
korean_m80 = pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\korean_v2\\korean_m80.csv")

In [10]:
data_merge = pd.merge(korean_f0, korean_f10, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f20, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f30, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f40, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f50, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f60, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f70, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_f80, on=['base_date', 'emd_cd'])

data_merge = pd.merge(data_merge, korean_m0, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m10, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m20, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m30, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m40, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m50, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m60, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m70, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, korean_m80, on=['base_date', 'emd_cd'])

data_merge = pd.merge(data_merge, data2_2, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data2_3, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data3, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data4, on=['base_date', 'emd_cd'])
data_merge = pd.merge(data_merge, data1, on=['base_date', 'emd_cd'])
data_merge = data_merge.drop(['total_pop'], 1)
data_merge

,base_date,emd_cd,f0_resd_pop,f0_work_pop,f0_visit_pop,f10_resd_pop,f10_work_pop,f10_visit_pop,f20_resd_pop,f20_work_pop,...,fe_resid_reg_pop,fe_foreign_pop,m_resid_reg_pop,m_foreign_pop,use_cnt_home,use_amt_home,use_cnt_out,use_amt_out,em_cnt,em_g
0,2019-11-30,50110250,595656.6904,75850.2547,244450.7884,470973.4183,58210.9861,190021.1853,320859.0111,35541.8894,...,10377,1353,11023,2396,301.620000,1.176953e+07,235.281250,7.540087e+06,620,2279550
1,2019-12-31,50110250,652151.7585,61500.4928,226945.5000,515642.8981,47098.8555,176849.9974,332910.6583,31108.4411,...,10354,1332,11011,2383,295.567742,1.175619e+07,239.472393,7.592077e+06,8178,31493650
2,2020-01-31,50110250,636463.4354,27210.6699,399362.9784,503238.4661,21032.9124,311991.9034,331482.3683,38458.0489,...,10369,1328,11004,2375,290.387097,1.201056e+07,226.043478,7.374075e+06,13042,49632850
3,2020-02-29,50110250,602907.6061,10699.8444,188481.2982,476706.5663,8391.0285,146962.6067,327308.5271,27226.7952,...,10341,1328,10985,2367,275.468966,1.023490e+07,224.297297,7.316381e+06,12264,46197050
4,2020-03-31,50110250,642258.4013,11387.4048,183057.2598,507820.4275,8839.0273,142351.2402,349132.2653,24328.9595,...,10310,1322,10970,2340,290.870968,1.066116e+07,232.694805,7.287016e+06,14316,52561750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,2021-02-28,50130620,106554.7117,515.3878,188420.8433,69829.5432,393.8831,147680.5081,124420.8042,69683.5399,...,1904,137,2013,119,74.918519,3.094460e+06,53.826087,1.723436e+06,4563,15566250
1630,2021-03-31,50130620,100670.5675,1651.9066,70897.6992,65973.4305,1264.1962,55205.7049,137125.1918,79959.4419,...,1918,137,2007,116,73.897959,3.175512e+06,60.849624,1.906193e+06,4920,17300600
1631,2021-04-30,50130620,94585.3320,1265.9660,79003.5640,61985.5337,967.5094,61643.0341,145934.6720,82938.6389,...,1904,135,2004,118,74.993151,2.940971e+06,61.398438,1.939595e+06,5256,17646850
1632,2021-05-31,50130620,102822.4935,2202.7842,141224.2364,67383.6726,1688.2686,110464.9987,158768.6248,89178.4000,...,1910,135,2021,112,80.437908,3.820713e+06,57.283688,1.826895e+06,6346,19494750
1633,2021-06-30,50130620,98120.6208,1145.2322,134030.4870,64302.3493,884.2088,104929.5216,148594.3741,78142.3558,...,1902,128,2013,109,79.462585,3.001846e+06,58.548387,1.696647e+06,6328,18753350

In [11]:
data_merge.columns = ['base_date', 'emd_cd', 
                      'korean_resd_f0', 'korean_work_f0', 'korean_visit_f0', 
                      'korean_resd_f10', 'korean_work_f10', 'korean_visit_f10', 
                      'korean_resd_f20', 'korean_work_f20', 'korean_visit_f20', 
                      'korean_resd_f30', 'korean_work_f30', 'korean_visit_f30', 
                      'korean_resd_f40', 'korean_work_f40', 'korean_visit_f40', 
                      'korean_resd_f50', 'korean_work_f50', 'korean_visit_f50', 
                      'korean_resd_f60', 'korean_work_f60', 'korean_visit_f60', 
                      'korean_resd_f70', 'korean_work_f70', 'korean_visit_f70', 
                      'korean_resd_f80', 'korean_work_f80', 'korean_visit_f80', 
                      'korean_resd_m0', 'korean_work_m0', 'korean_visit_m0', 
                      'korean_resd_m10', 'korean_work_m10', 'korean_visit_m10', 
                      'korean_resd_m20', 'korean_work_m20', 'korean_visit_m20', 
                      'korean_resd_m30', 'korean_work_m30', 'korean_visit_m30', 
                      'korean_resd_m40', 'korean_work_m40', 'korean_visit_m40', 
                      'korean_resd_m50', 'korean_work_m50', 'korean_visit_m50', 
                      'korean_resd_m60', 'korean_work_m60', 'korean_visit_m60', 
                      'korean_resd_m70', 'korean_work_m70', 'korean_visit_m70', 
                      'korean_resd_m80', 'korean_work_m80', 'korean_visit_m80', 
                      'long_term_frgn_resd', 'long_term_frgn_work', 'long_term_frgn_visit', 
                      'short_term_frgn_visit', 
                      'resident_fe_korean', 'resident_fe_frgn', 'resident_m_korean', 'resident_m_frgn', 
                      'card_cnt_home', 'card_amt_home', 'card_cnt_out', 'card_amt_out', 
                      'waste_cnt', 'waste_amt']
data_merge

,base_date,emd_cd,korean_resd_f0,korean_work_f0,korean_visit_f0,korean_resd_f10,korean_work_f10,korean_visit_f10,korean_resd_f20,korean_work_f20,...,resident_fe_korean,resident_fe_frgn,resident_m_korean,resident_m_frgn,card_cnt_home,card_amt_home,card_cnt_out,card_amt_out,waste_cnt,waste_amt
0,2019-11-30,50110250,595656.6904,75850.2547,244450.7884,470973.4183,58210.9861,190021.1853,320859.0111,35541.8894,...,10377,1353,11023,2396,301.620000,1.176953e+07,235.281250,7.540087e+06,620,2279550
1,2019-12-31,50110250,652151.7585,61500.4928,226945.5000,515642.8981,47098.8555,176849.9974,332910.6583,31108.4411,...,10354,1332,11011,2383,295.567742,1.175619e+07,239.472393,7.592077e+06,8178,31493650
2,2020-01-31,50110250,636463.4354,27210.6699,399362.9784,503238.4661,21032.9124,311991.9034,331482.3683,38458.0489,...,10369,1328,11004,2375,290.387097,1.201056e+07,226.043478,7.374075e+06,13042,49632850
3,2020-02-29,50110250,602907.6061,10699.8444,188481.2982,476706.5663,8391.0285,146962.6067,327308.5271,27226.7952,...,10341,1328,10985,2367,275.468966,1.023490e+07,224.297297,7.316381e+06,12264,46197050
4,2020-03-31,50110250,642258.4013,11387.4048,183057.2598,507820.4275,8839.0273,142351.2402,349132.2653,24328.9595,...,10310,1322,10970,2340,290.870968,1.066116e+07,232.694805,7.287016e+06,14316,52561750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,2021-02-28,50130620,106554.7117,515.3878,188420.8433,69829.5432,393.8831,147680.5081,124420.8042,69683.5399,...,1904,137,2013,119,74.918519,3.094460e+06,53.826087,1.723436e+06,4563,15566250
1630,2021-03-31,50130620,100670.5675,1651.9066,70897.6992,65973.4305,1264.1962,55205.7049,137125.1918,79959.4419,...,1918,137,2007,116,73.897959,3.175512e+06,60.849624,1.906193e+06,4920,17300600
1631,2021-04-30,50130620,94585.3320,1265.9660,79003.5640,61985.5337,967.5094,61643.0341,145934.6720,82938.6389,...,1904,135,2004,118,74.993151,2.940971e+06,61.398438,1.939595e+06,5256,17646850
1632,2021-05-31,50130620,102822.4935,2202.7842,141224.2364,67383.6726,1688.2686,110464.9987,158768.6248,89178.4000,...,1910,135,2021,112,80.437908,3.820713e+06,57.283688,1.826895e+06,6346,19494750
1633,2021-06-30,50130620,98120.6208,1145.2322,134030.4870,64302.3493,884.2088,104929.5216,148594.3741,78142.3558,...,1902,128,2013,109,79.462585,3.001846e+06,58.548387,1.696647e+06,6328,18753350

In [12]:
data_merge.to_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\ver_2_2_merge_data.csv", index_label=False)

In [13]:
pd.read_csv("C:\\Users\\asus\\BigContest\\files\\data_preprocessing\\ver_2_2_merge_data.csv")

,base_date,emd_cd,korean_resd_f0,korean_work_f0,korean_visit_f0,korean_resd_f10,korean_work_f10,korean_visit_f10,korean_resd_f20,korean_work_f20,...,resident_fe_korean,resident_fe_frgn,resident_m_korean,resident_m_frgn,card_cnt_home,card_amt_home,card_cnt_out,card_amt_out,waste_cnt,waste_amt
0,2019-11-30,50110250,595656.6904,75850.2547,244450.7884,470973.4183,58210.9861,190021.1853,320859.0111,35541.8894,...,10377,1353,11023,2396,301.620000,1.176953e+07,235.281250,7.540087e+06,620,2279550
1,2019-12-31,50110250,652151.7585,61500.4928,226945.5000,515642.8981,47098.8555,176849.9974,332910.6583,31108.4411,...,10354,1332,11011,2383,295.567742,1.175619e+07,239.472393,7.592077e+06,8178,31493650
2,2020-01-31,50110250,636463.4354,27210.6699,399362.9784,503238.4661,21032.9124,311991.9034,331482.3683,38458.0489,...,10369,1328,11004,2375,290.387097,1.201056e+07,226.043478,7.374075e+06,13042,49632850
3,2020-02-29,50110250,602907.6061,10699.8444,188481.2982,476706.5663,8391.0285,146962.6067,327308.5271,27226.7952,...,10341,1328,10985,2367,275.468966,1.023490e+07,224.297297,7.316381e+06,12264,46197050
4,2020-03-31,50110250,642258.4013,11387.4048,183057.2598,507820.4275,8839.0273,142351.2402,349132.2653,24328.9595,...,10310,1322,10970,2340,290.870968,1.066116e+07,232.694805,7.287016e+06,14316,52561750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629,2021-02-28,50130620,106554.7117,515.3878,188420.8433,69829.5432,393.8831,147680.5081,124420.8042,69683.5399,...,1904,137,2013,119,74.918519,3.094460e+06,53.826087,1.723436e+06,4563,15566250
1630,2021-03-31,50130620,100670.5675,1651.9066,70897.6992,65973.4305,1264.1962,55205.7049,137125.1918,79959.4419,...,1918,137,2007,116,73.897959,3.175512e+06,60.849624,1.906193e+06,4920,17300600
1631,2021-04-30,50130620,94585.3320,1265.9660,79003.5640,61985.5337,967.5094,61643.0341,145934.6720,82938.6389,...,1904,135,2004,118,74.993151,2.940971e+06,61.398438,1.939595e+06,5256,17646850
1632,2021-05-31,50130620,102822.4935,2202.7842,141224.2364,67383.6726,1688.2686,110464.9987,158768.6248,89178.4000,...,1910,135,2021,112,80.437908,3.820713e+06,57.283688,1.826895e+06,6346,19494750
1633,2021-06-30,50130620,98120.6208,1145.2322,134030.4870,64302.3493,884.2088,104929.5216,148594.3741,78142.3558,...,1902,128,2013,109,79.462585,3.001846e+06,58.548387,1.696647e+06,6328,18753350